#ifndef DEFINE_CAST_H
#define DEFINE_CAST_H

#define _______ T_CastType::_______
#define S___I__ T_CastType::S___I__
#define S___L__ T_CastType::S___L__
#define S___F__ T_CastType::S___F__
#define S___D__ T_CastType::S___D__
#define S___SC_ T_CastType::S___SC_
#define S___IC_ T_CastType::S___IC_
#define S___LC_ T_CastType::S___LC_
#define S___FC_ T_CastType::S___FC_
#define S___DC_ T_CastType::S___DC_
#define S___SR_ T_CastType::S___SR_
#define S___SCR T_CastType::S___SCR
#define I___S__ T_CastType::I___S__
#define I___L__ T_CastType::I___L__
#define I___F__ T_CastType::I___F__
#define I___D__ T_CastType::I___D__
#define I___SC_ T_CastType::I___SC_
#define I___IC_ T_CastType::I___IC_
#define I___LC_ T_CastType::I___LC_
#define I___FC_ T_CastType::I___FC_
#define I___DC_ T_CastType::I___DC_
#define I___IR_ T_CastType::I___IR_
#define I___ICR T_CastType::I___ICR
#define L___S__ T_CastType::L___S__
#define L___I__ T_CastType::L___I__
#define L___F__ T_CastType::L___F__
#define L___D__ T_CastType::L___D__
#define L___SC_ T_CastType::L___SC_
#define L___IC_ T_CastType::L___IC_
#define L___LC_ T_CastType::L___LC_
#define L___FC_ T_CastType::L___FC_
#define L___DC_ T_CastType::L___DC_
#define L___LR_ T_CastType::L___LR_
#define L___LCR T_CastType::L___LCR
#define F___S__ T_CastType::F___S__
#define F___I__ T_CastType::F___I__
#define F___L__ T_CastType::F___L__
#define F___D__ T_CastType::F___D__
#define F___SC_ T_CastType::F___SC_
#define F___IC_ T_CastType::F___IC_
#define F___LC_ T_CastType::F___LC_
#define F___FC_ T_CastType::F___FC_
#define F___DC_ T_CastType::F___DC_
#define F___FR_ T_CastType::F___FR_
#define F___FCR T_CastType::F___FCR
#define D___S__ T_CastType::D___S__
#define D___I__ T_CastType::D___I__
#define D___L__ T_CastType::D___L__
#define D___F__ T_CastType::D___F__
#define D___SC_ T_CastType::D___SC_
#define D___IC_ T_CastType::D___IC_
#define D___LC_ T_CastType::D___LC_
#define D___FC_ T_CastType::D___FC_
#define D___DC_ T_CastType::D___DC_
#define D___DR_ T_CastType::D___DR_
#define D___DCR T_CastType::D___DCR
#define SC__S__ T_CastType::SC__S__
#define SC__I__ T_CastType::SC__I__
#define SC__L__ T_CastType::SC__L__
#define SC__F__ T_CastType::SC__F__
#define SC__D__ T_CastType::SC__D__
#define SC__IC_ T_CastType::SC__IC_
#define SC__LC_ T_CastType::SC__LC_
#define SC__FC_ T_CastType::SC__FC_
#define SC__DC_ T_CastType::SC__DC_
#define IC__S__ T_CastType::IC__S__
#define IC__I__ T_CastType::IC__I__
#define IC__L__ T_CastType::IC__L__
#define IC__F__ T_CastType::IC__F__
#define IC__D__ T_CastType::IC__D__
#define IC__SC_ T_CastType::IC__SC_
#define IC__LC_ T_CastType::IC__LC_
#define IC__FC_ T_CastType::IC__FC_
#define IC__DC_ T_CastType::IC__DC_
#define LC__S__ T_CastType::LC__S__
#define LC__I__ T_CastType::LC__I__
#define LC__L__ T_CastType::LC__L__
#define LC__F__ T_CastType::LC__F__
#define LC__D__ T_CastType::LC__D__
#define LC__SC_ T_CastType::LC__SC_
#define LC__IC_ T_CastType::LC__IC_
#define LC__FC_ T_CastType::LC__FC_
#define LC__DC_ T_CastType::LC__DC_
#define FC__S__ T_CastType::FC__S__
#define FC__I__ T_CastType::FC__I__
#define FC__L__ T_CastType::FC__L__
#define FC__F__ T_CastType::FC__F__
#define FC__D__ T_CastType::FC__D__
#define FC__SC_ T_CastType::FC__SC_
#define FC__IC_ T_CastType::FC__IC_
#define FC__LC_ T_CastType::FC__LC_
#define FC__DC_ T_CastType::FC__DC_
#define DC__S__ T_CastType::DC__S__
#define DC__I__ T_CastType::DC__I__
#define DC__L__ T_CastType::DC__L__
#define DC__F__ T_CastType::DC__F__
#define DC__D__ T_CastType::DC__D__
#define DC__SC_ T_CastType::DC__SC_
#define DC__IC_ T_CastType::DC__IC_
#define DC__LC_ T_CastType::DC__LC_
#define DC__FC_ T_CastType::DC__FC_
#define SR__S__ T_CastType::SR__S__
#define SR__I__ T_CastType::SR__I__
#define SR__L__ T_CastType::SR__L__
#define SR__F__ T_CastType::SR__F__
#define SR__D__ T_CastType::SR__D__
#define SR__SC_ T_CastType::SR__SC_
#define SR__IC_ T_CastType::SR__IC_
#define SR__LC_ T_CastType::SR__LC_
#define SR__FC_ T_CastType::SR__FC_
#define SR__DC_ T_CastType::SR__DC_
#define IR__S__ T_CastType::IR__S__
#define IR__I__ T_CastType::IR__I__
#define IR__L__ T_CastType::IR__L__
#define IR__F__ T_CastType::IR__F__
#define IR__D__ T_CastType::IR__D__
#define IR__SC_ T_CastType::IR__SC_
#define IR__IC_ T_CastType::IR__IC_
#define IR__LC_ T_CastType::IR__LC_
#define IR__FC_ T_CastType::IR__FC_
#define IR__DC_ T_CastType::IR__DC_
#define LR__S__ T_CastType::LR__S__
#define LR__I__ T_CastType::LR__I__
#define LR__L__ T_CastType::LR__L__
#define LR__F__ T_CastType::LR__F__
#define LR__D__ T_CastType::LR__D__
#define LR__SC_ T_CastType::LR__SC_
#define LR__IC_ T_CastType::LR__IC_
#define LR__LC_ T_CastType::LR__LC_
#define LR__FC_ T_CastType::LR__FC_
#define LR__DC_ T_CastType::LR__DC_
#define FR__S__ T_CastType::FR__S__
#define FR__I__ T_CastType::FR__I__
#define FR__L__ T_CastType::FR__L__
#define FR__F__ T_CastType::FR__F__
#define FR__D__ T_CastType::FR__D__
#define FR__SC_ T_CastType::FR__SC_
#define FR__IC_ T_CastType::FR__IC_
#define FR__LC_ T_CastType::FR__LC_
#define FR__FC_ T_CastType::FR__FC_
#define FR__DC_ T_CastType::FR__DC_
#define DR__S__ T_CastType::DR__S__
#define DR__I__ T_CastType::DR__I__
#define DR__L__ T_CastType::DR__L__
#define DR__F__ T_CastType::DR__F__
#define DR__D__ T_CastType::DR__D__
#define DR__SC_ T_CastType::DR__SC_
#define DR__IC_ T_CastType::DR__IC_
#define DR__LC_ T_CastType::DR__LC_
#define DR__FC_ T_CastType::DR__FC_
#define DR__DC_ T_CastType::DR__DC_
#define SCR_S__ T_CastType::SCR_S__
#define SCR_I__ T_CastType::SCR_I__
#define SCR_L__ T_CastType::SCR_L__
#define SCR_F__ T_CastType::SCR_F__
#define SCR_D__ T_CastType::SCR_D__
#define SCR_SC_ T_CastType::SCR_SC_
#define SCR_IC_ T_CastType::SCR_IC_
#define SCR_LC_ T_CastType::SCR_LC_
#define SCR_FC_ T_CastType::SCR_FC_
#define SCR_DC_ T_CastType::SCR_DC_
#define ICR_S__ T_CastType::ICR_S__
#define ICR_I__ T_CastType::ICR_I__
#define ICR_L__ T_CastType::ICR_L__
#define ICR_F__ T_CastType::ICR_F__
#define ICR_D__ T_CastType::ICR_D__
#define ICR_SC_ T_CastType::ICR_SC_
#define ICR_IC_ T_CastType::ICR_IC_
#define ICR_LC_ T_CastType::ICR_LC_
#define ICR_FC_ T_CastType::ICR_FC_
#define ICR_DC_ T_CastType::ICR_DC_
#define LCR_S__ T_CastType::LCR_S__
#define LCR_I__ T_CastType::LCR_I__
#define LCR_L__ T_CastType::LCR_L__
#define LCR_F__ T_CastType::LCR_F__
#define LCR_D__ T_CastType::LCR_D__
#define LCR_SC_ T_CastType::LCR_SC_
#define LCR_IC_ T_CastType::LCR_IC_
#define LCR_LC_ T_CastType::LCR_LC_
#define LCR_FC_ T_CastType::LCR_FC_
#define LCR_DC_ T_CastType::LCR_DC_
#define FCR_S__ T_CastType::FCR_S__
#define FCR_I__ T_CastType::FCR_I__
#define FCR_L__ T_CastType::FCR_L__
#define FCR_F__ T_CastType::FCR_F__
#define FCR_D__ T_CastType::FCR_D__
#define FCR_SC_ T_CastType::FCR_SC_
#define FCR_IC_ T_CastType::FCR_IC_
#define FCR_LC_ T_CastType::FCR_LC_
#define FCR_FC_ T_CastType::FCR_FC_
#define FCR_DC_ T_CastType::FCR_DC_
#define DCR_S__ T_CastType::DCR_S__
#define DCR_I__ T_CastType::DCR_I__
#define DCR_L__ T_CastType::DCR_L__
#define DCR_F__ T_CastType::DCR_F__
#define DCR_D__ T_CastType::DCR_D__
#define DCR_SC_ T_CastType::DCR_SC_
#define DCR_IC_ T_CastType::DCR_IC_
#define DCR_LC_ T_CastType::DCR_LC_
#define DCR_FC_ T_CastType::DCR_FC_
#define DCR_DC_ T_CastType::DCR_DC_

#endif
